tweets = [
    "I bet you're the kind of guy that would fuck a person in the ass and not even have the goddamn common courtesy to give him a reach-around. I'll be watching you.",
    "I am Gunnery Sergeant Hartman, your senior drill instructor. From now on you will speak only when spoken to, and the first and last words out of your filthy sewers will be 'Sir'. Do you maggots understand that?",
    "Bullshit, I can't hear you. Sound off like you got a pair!",
    "If you ladies leave my island, if you survive recruit training, you will be a weapon. You will be a minister of death praying for war. But until that day, you are pukes.",
    "You are the lowest form of life on Earth. You are not even human fucking beings. You are nothing but unorganized grab-asstic pieces of amphibian shit!",
    "Because I am hard, you will not like me. But the more you hate me, the more you will learn. I am hard but I am fair.",
    "There is no racial bigotry here. I do not look down on niggers, kikes, wops or greasers. Here you are all equally worthless.",
    "And my orders are to weed out all non-hackers who do not pack the gear to serve in my beloved Corps. Do you maggots understand that?",
    "Did your parents have any children that lived?",
    "You're so ugly you could be a modern art masterpiece!",
    "That name sounds like royalty. Are you royalty?",
    "Do you suck dicks?",
    "Bullshit. I bet you could suck a golf ball through a garden hose.",
    "Five-foot-nine, I didn't know they stacked shit that high!",
    "What is this Mickey Mouse shit?",
    "What is your major malfunction, numbnuts? Didn't Mommy and Daddy show you enough attention when you were a child?",
    "Holy dog shit! Texas? Only steers and queers come from Texas, Private Cowboy, and you don't look much like a steer to me, so that kinda narrows it down. Do you suck dicks?",
    "Are you a peter puffer?",
    "Today, you people are no longer maggots. Today, you are Marines. You're part of a brotherhood.",
    "Why you little maggot, you make me want to vomit!",
    "You Goddamn communist heathen, you had best sound off that you love the Virgin Mary, or I'm gonna stomp your guts out!",
    "...don't make any fucking effort to get to the top of the fucking obstacle. If God would have wanted you up there he would have miracled your ass up there by now, wouldn't he?",
    "Tonight, you pukes will sleep with your rifles. You will give your rifle a girl's name because this is the only pussy you people are going to get.",
    "Your days of finger-banging ol' Mary-Jane Rottencrotch through her pretty pink panties are over! You're married to this piece. This weapon of iron and wood. And you will be faithful.",
    "Today... is Christmas! There will be a magic show at zero-nine-thirty! Chaplain Charlie will tell you about how the free world will conquer Communism with the aid of God and a few Marines!",
    "God has a hard-on for Marines because we kill everything we see! He plays His games, we play ours!",
    "To show our appreciation for so much power, we keep heaven packed with fresh souls! God was here before the Marine Corps!",
    "So you can give your heart to Jesus, but your ass belongs to the Corps! Do you ladies understand?",
    "The deadliest weapon in the world is a Marine and his rifle. It is your killer instinct which must be harnessed if you expect to survive in combat.",
    "Your rifle is only a tool. It is a hard heart that kills.",
    "If your killer instincts are not clean and strong you will hesitate at the moment of truth. You will not kill.",
    "You will become dead marines and then you will be in a world of shit because marines are not allowed to die without permission. Do you maggots understand?",
    "Those individuals showed what one motivated Marine and his rifle can do. And before you ladies leave my Island, you will all be able to do the same thing.",
    "Were you born a fat, slimy, scumbag puke piece o' shit, Private Pyle, or did you have to work on it?",
    "Well there's one thing that you won't like, Private Snowball: they don't serve fried chicken and watermelon on a daily basis in my mess hall.",
    "...you are a disgusting fat body, Private Pyle!",
    "Private Pyle has dishonored himself and dishonored the platoon. I have tried to help him. But I have failed. I have failed because YOU have not helped me.",
    "I'm gonna give you three seconds; exactly three-fucking-seconds to wipe that stupid looking grin off your face or I will gouge out your eyeballs and skull-fuck you! ONE! TWO! THREE!",
    "Bullshit! Get on your knees scumbag!",
    "Private Pyle you had best square your ass away and start shitting me Tiffany cufflinks or I will definitely fuck you up!",
    "Well, thank you very much! Can I be in charge for a while?",
    "You best unfuck yourself or I will unscrew your head and shit down your NECK!",
    "Are you quitting on me? Well, are you? Then quit, you slimy fucking walrus-looking piece of shit! Get the fuck off of my obstacle! Get the fuck down off of my obstacle!",
    "I'm going to rip your balls off, so you cannot contaminate the rest of the world! I will motivate you, Private Pyle, IF IT SHORT-DICKS EVERY CANNIBAL ON THE CONGO!",
    "Eskimo pussy is mighty cold.",
    "Private Pyle, you are definitely born again hard! Hell, I may even allow you to serve as a rifleman in my beloved Corps.",
    "Those individuals showed what one motivated marine and his rifle can do! And before you ladies leave my island, you will be able to do the same thing!",
    "Are you shook up? Are you nervous?",
    "If it wasn't for dickheads like you, there wouldn't be any thievery in this world, would there?",
    "Get your fat ass up there! I'll bet if there was some pussy up there you would get up there, wouldn't you?",
    "Private Pyle, your ass looks like about a hundred and fifty pounds of chewed bubblegum!",
    "Come on, Pyle! Pull! Pull! You mean to tell me you can't do one single pull up Pyle? You are a worthless piece of shit, Pyle! Get outta my face!",
    "Do you feel dizzy? Do you feel faint! Jesus H. Christ! I think you've got a hard-on!",
    "Bullshit. It looks to me like the best part of you ran down the crack of your mama's ass and ended up as a brown stain on the mattress.",
    "I want that head so sanitary and squared-away that the Virgin Mary herself would be proud to go in and take a dump.",
    "Come on, guys. Assholes and elbows.",
    "Well, no shit. What have we got here, a fucking comedian? Private Joker? I admire your honesty. Hell, I like you. You can come over to my house and fuck my sister.",
    "BULLSHIT YOU DIDN'T CONVINCE ME! LET ME SEE YOUR *REAL* WAR FACE!",
    "You little piece of shit! You look like a fucking worm!",
    "Who's the slimy little communist shit twinkle-toed cocksucker down here, who just signed his own death warrant? Nobody, huh? The fairy fucking godmother said it!",
    "Out-fuckingstanding! I will P.T. you all until you fucking die! I'll P.T. you until your assholes are sucking buttermilk.",
    "Get up here, fatboy! Quickly! Move it up! Move it up, Pyle! Move it up! You climb obstacles like old people fuck.",
    "Reveille! Reveille! Reveille! Drop your cocks and grab your socks! ",
    "Move it up! Quickly! Hustle up! The fucking war will be over by the time we get out there, won't it, Private Pyle? Move it!"
]